[package]
name = "bakery_model4"
version = "0.1.0"
edition = "2021"

[dependencies]
vantage-config = { path = "../vantage-config", features = ["decimal"] }
vantage-surrealdb = { path = "../vantage-surrealdb" }
surreal-client = { path = "../surreal-client", features = ["decimal"] }
vantage-table = { path = "../vantage-table" }
vantage-core = { path = "../vantage-core" }
vantage-expressions = { path = "../vantage-expressions" }
vantage-dataset = { path = "../vantage-dataset" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
clap = { version = "4.5", features = ["derive"] }
