[package]
name = "vantage-types"
version = "0.1.0"
edition = "2021"



[dependencies]
paste = "1.0"
vantage-types-persistence = { path = "./persistence" }

[dev-dependencies]
ciborium = { version = "0.2", features = ["std"] }
serde = { version = "1.0", features = ["derive"] }
url = { version = "2.5", features = ["serde"] }
serde_json = "1.0.145"
indexmap = "2.0"
rust_decimal = "1.0"
