[package]
edition = "2024"
name = "vantage-expressions"
version = "0.3.0"
license = "MIT OR Apache-2.0"
authors = ["Romans Malinovskis <me@nearly.guru>"]
description = "Database agnostic expressions"
documentation = "https://docs.rs/vantage"
homepage = "https://romaninsh.github.io/vantage"
repository = "https://github.com/romaninsh/vantage"
readme = "../README.md"

[lib]
doctest = false

[dependencies]
async-trait = "0.1"
chrono = { version = "0.4", features = ["serde"], optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.145"
thiserror = "2.0.17"
vantage-core = { path = "../vantage-core" }
vantage-dataset = { path = "../vantage-dataset" }

[dev-dependencies]
tokio = { version = "1.48", features = ["full"] }
tokio-test = "0.4"
chrono = { version = "0.4", features = ["serde"] }
